language: cpp
compiler: gcc
dist: trusty
script:
  - sh -x bootstrap.sh
  - env CFLAGS="-Wall -Wextra -Wno-reorder" CPPFLAGS="-Wall -Wextra -Wno-reorder" ./configure --disable-systemd
  - make
  - strace -f -s300 -o/tmp/bla sh tools/test.sh || true
  - cat /tmp/bla
  - exit 1
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libev-dev
    - libusb-1.0-0-dev
